config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get '/posts' => 'posts#index'
  get '/posts/new' => 'posts#new', as: 'new_post'
  post '/posts' => 'posts#create'
  get '/posts/:id' => 'posts#show', as: 'show_post'
  delete '/posts/:id' => 'posts#destroy'

  get '/comments' => 'comments#index'
  post '/comments' => 'comments#create'
  resources :users
  resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments

  validates :title, :presence => {:message => "must be present"}
  validates :link, :presence => {:message => "must be present"}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  validates :username, :presence => {:message => "must be present"}, :uniqueness => {:message => "must be unique"}

  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    if logged_in?
      User.find(session[:user_id])
    end
  end

  def logged_in?
    !!session[:user_id]
  end

end

app/controllers/concerns/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def create
    post = Post.find_by(id: params[:comment][:post])
    if logged_in?
      user = User.find_by(id: session[:user_id])
      user.comments.create(body: params[:comment][:body])
      redirect_to show_post_path(post)
    else
      flash[:error] = "Login to add comment"
      redirect_to new_session_path
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/concerns/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.build(posts_params)
    if post.save
      redirect_to show_post_path("#{post.id}")
    else
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
  end

  def destroy
    user_id = session[:user_id]
    post = Post.find(params[:id])
    if user_id == current_user.id
      post.destroy
    end
    redirect_to posts_path
  end

  private
    def posts_params
      params.require(:post).permit(:title, :link)
    end

end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params[:user]
    user = User.find_by(username: user_params[:username])
    if user && user.password == user_params[:password]
      session[:user_id] = user.id
      flash[:message] = "Welcome #{user.username}!!"
      redirect_to posts_path
    else
      flash[:error] = "Incorrect username or password"
      redirect_to new_session_path
    end
  end

  def destroy
    session.clear
    redirect_to posts_path
  end

end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to "/users/#{user.id}"
    else
      flash[:error] = "Username already taken."
      redirect_to "/users/new"
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for comment do |f| %>
<%= f.hidden_field :post, value: post.id %>
<%= f.label :comment %>
<%= f.text_field :body %>
<%= f.submit "Submit comment" %>
<% end %>

app/views/comments/index.html.erb
<h3> Here's what people are saying... </h3>

<% @comments.each do |comment| %>
  <%= link_to comment.post.title, "http://" + comment.post.link %><br/>
  <%= comment.body %> | <%= comment.user.username %><br/>
  <div id='spacer'></div>
<% end %>

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
<%= f.hidden_field :post, value: @post.id %>
<%= f.label :body %>
<%= f.text_field :body %>
<%= f.submit "Submit comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <div id="nav-bar">
  <title>HackerNewsOnRails</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= link_to "Comments", comments_path %> |
    <%= link_to "Posts", posts_path %> |
    <% if logged_in? %>
    <%= link_to "Log out", session_path(current_user), :method => :delete %> |
    <% else %>
    <%= link_to "Sign Up", new_user_path %> |
    <%= link_to "Login", new_session_path %>
    <% end %>
  </div>
</head>

<body>

<div id="container">
  <%= flash[:message] %>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <p id="post-title"><%= link_to post.title, "http://" + post.link %> | <span id="link">(<%= post.link %>)</span></p>
  <p id="post-info">Submitted by <%= post.user.username %> on <%= post.created_at.strftime("%m/%d/%Y") %> | <%= link_to "Comments", show_post_path(post.id) %></p>
<% end %>
<br/>
<% if logged_in? %>
  <%= link_to "New Post", new_post_path %>
<% else %>
  <%= link_to "Login to create new post", new_session_path %>
<% end %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.submit "Submit Post" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<% if @post.user == current_user %>
  <%= link_to "Delete", show_post_path(@post), :method => :delete %>
<% end %>

<%= render :partial => 'comments/form', locals: { post: @post, comment: @comment } %>

<% @post.comments.each do |comment| %>
<li><%= comment.body %></li>
<%= comment.created_at.strftime("%m/%d/%Y") %> | <%= comment.user.username %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: { id: 'register' } do |f| %>

<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :confirm_password %>
<%= f.password_field :password_confirmation  %>
<%= f.submit "Sign up!" %>
<% end %>

app/views/users/new.html.erb
<h3>Sign in!</h3>
<%= flash[:error] %>

<%= render :partial => 'users/form' %>

app/views/users/show.html.erb
<h3>Welcome <%= @user.username %> </h3>